### ISSUE TITLE
Dynatrace Entity Model - lookup

### ISSUE THREAD

**Issue by michal-dec** [michaljonko/dynatrace-log4j2-appender#1]
As a Dynatrace customer I would like to have automatic lookup that will enrich log events with attributes containing process group instance ID and host ID (assuming that OneAgent is deployed on host where application is running). Similar to Docker Lookup.

**Comment by michaljonko** [comment]
Hi @michal-dec .
Please check version 0.0.4 - DynatraceLookup has been introduced.

**Comment by michaljonko** [comment]
Changes in:
https://github.com/michaljonko/dynatrace-log4j2-appender/commit/e3e2d45b045af8164223644c81e9ba00778cb535
