### ISSUE TITLE
big delay in log ingestion

### ISSUE THREAD

**Issue by CurryAri** [michaljonko/dynatrace-log4j2-appender#2]
The logs are arriving in a 3 hour delay to dynatrace since when we sent them. 
Seems like it might be due to the timezone of the http client used in the appender, it is set on UTC and we are sending from an IDT local machine.  you can see in the picture that the time it shows is 3 hours behind the current time. is there any solution for this? thanks

<img width="773" alt="MicrosoftTeams-image (4)" src="https://user-images.githubusercontent.com/72021211/138090206-a8e3e29e-20a7-4b6e-ba66-efd31fd9b29d.png">

**Comment by michaljonko** [comment]
I'll check it. Which time zone is used in the system?

**Comment by CurryAri** [comment]
Hi, for some reason even when we changed the timezone to UTC in our local testing environment the delay remained.
this was resolved afer we deployed it to our azure webapp, which is on UTC timezone.
